<?php

/* * **********************************
 * NAME:IndexController
 * DESC:
 *  トップページ用コントローラ
 * NOTICE:
 * CREATE: 2016.10.11 aoyama
 * *********************************** */
class IndexController extends PublicOpenControllerFrame {

	private $sGroup;

	/* Constructor */
	public function __construct() {
		parent::__construct();
		$this->sGroup = 'index';
	}

	/*	 * **********************************
	 * NAME  : exec
	 * INPUT : NONE
	 * OUTPUT: NONE
	 * DESC  :
	 * NOTICE:
	 * CREATE: 2016.10.11 aoyama
	 * *********************************** */
	public function index() {
		
		
		
	}

}

?>
