<?php

/* ---------------------------------------
  database
  ---------------------------------------- */
$config["DB"] = array(
	"DBMS" => "mysql",
	"HOST" => "152.69.193.189",
	"PORT" => "3306",
	"CHAR_SET" => "utf8",
	"NAME" => "happy_sns",
	"USER_ID" => "happy_sns",
	"USER_PW" => "bhG4ka8)Rpsv",

	"IS_CHECK_TABLES" => false		//テーブルチェック&なければ作成処理のON/OFF(この処理で80ms以上時間を要する)
);

?>
