<?php

/* * **********************************
 * NAME:TestApiController
 * DESC:
 * NOTICE:
 * CREATE: 2016.07.11 hesaka
 * *********************************** */
class TestApiController extends InternalApiCloseControllerFrame {

	/* Constructor */
	public function __construct() {
		parent::__construct();
	}

	/*	 * **********************************
	 * NAME  : exec
	 * INPUT : NONE
	 * OUTPUT: NONE
	 * DESC  :
	 * NOTICE:
	 * CREATE: 2016.07.11 hesaka
	 * *********************************** */
	public function exec() {
	}

}

?>
